name: Auto-Assign Random Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grants access to modify PRs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Auto Assign PR
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: ".github/auto-assign.yml"
